name: CI Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test-ci

  build:
    # call the build job from the build.yaml workflow
    uses: ./.github/workflows/build.yaml
    with:
      site-origin: https://ryojerryyu.github.io
      site-base-path: /blog-next
      # a CI build, skip uploading artifacts and fetch minimal history
      is-ci-build: true
