name: Archive Notion Clipper

on: 
  pull_request:
    branches-ignore:
      - 'dependabot/**'
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Archive Notion Clipper
        uses: RyoJerryYu/notion-clipper-archiver@v1
        id: notion_clipper_archive
        with:
          notion_token: ${{ secrets.NOTION_TOKEN }}
          database_id: ${{ secrets.DATABASE_ID }}
          save_dir: ./data
          file_name: clips.json

      - name: Debug
        run: |
          ls -la ./data
          cat ./data/clips.json

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: notion-clipper-archive
          path: ${{ steps.notion_clipper_archive.outputs.save_path }}
