name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches-ignore:
      - 'dependabot/**'
  workflow_dispatch:

env:
  NEXT_PUBLIC_SITE_ORIGIN: https://ryojerryyu.github.io
  NEXT_PUBLIC_SITE_BASE_PATH: /blog-next
jobs:
  build: # Job name
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3
        with:
          # git-restore-mtime-bare uses the ref log to find the correct timestamp
          # for each file. This requires a full git history. The default value (1)
          # creates a shallow checkout.
          fetch-depth: 0
          lfs: true
      # Fix timestamps
      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@v1

        
      # a standard step for GitHub actions on Node
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v3
        with:
          # update the Node version to meet your needs
          node-version: 16
          cache: yarn

      - name: Build
        run: |
          yarn install
          yarn build
          touch out/.nojekyll

      - name: Deploy
        # https://github.com/JamesIves/github-pages-deploy-action
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out