name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches-ignore:
      - 'dependabot/**'
  workflow_dispatch:

jobs:
  build:
    if: github.actor != 'dependabot[bot]'
    uses: ./.github/workflows/build.yaml
    with:
      site-origin: https://ryojerryyu.github.io
      site-base-path: /blog-next

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # Deploy to gh-pages should be in a git directory

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: blog-next
          path: out
      
      - name: Debug
        run: |
          ls -al out
          cat out/sitemap.xml

      - name: Deploy
        # https://github.com/JamesIves/github-pages-deploy-action
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out